kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment 
  Namespace: testing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: frontend
        images: 